name: Test Galicia Seguros

on:
  push:
    branches: [main, dev]
    
jobs:
  start-pipeline:
    runs-on: ubuntu-latest 
    #mac-latest windows-latest
    #permissions: #Verificamos si la cuenta que lo ejecuta tiene estos permisos
    #  contents: read
    #  packages: write
    steps:
      - run: echo "Hola Mundo"
